import type { Issue } from "@/types/issue";

import d0 from "./2026-08-23";
import d1 from "./2026-08-20";

// AUTO-GENERATED by scripts/build-weekly-issue.ts — do not edit by hand.
// Drafts are reviewable weekly issues that are not yet published to /blog.
export const drafts: Issue[] = [d0, d1].sort((a, b) => b.isoDate.localeCompare(a.isoDate));

export function getDraft(slug: string): Issue | undefined {
  return drafts.find((d) => d.slug === slug);
}

export function getDraftSlugs(): string[] {
  return drafts.map((d) => d.slug);
}
